# pvc => PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  这个是指 mysql 要用的东西
  name: webook-mysql-live-claim
spec:
#  这个名字可以随便写
  storageClassName: suibian
  accessModes:
#     一个（POD）读写
    - ReadWriteOnce
#     多个读，一个写
#    - ReadOnlyMany
#     多个读写
#    - ReadWriteMany
  resources:
    requests:
#      1 GB
      storage: 1Gi
  